[platformio]
default_envs = cardputer_adv
platforms_dir = .pio-core/platforms
packages_dir = .pio-core/packages
cache_dir = .pio-core/cache

[env:cardputer_adv]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags =
    --no-stub
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_unflags =
    -DARDUINO_USB_MODE=1
build_flags =
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
    -DCORE_DEBUG_LEVEL=1
    -Wall
    -Wextra
    -Wformat=2
lib_deps =
    https://github.com/m5stack/M5Cardputer.git#f1392858b9994c3547120e602a57d3553d16ab01
    https://github.com/m5stack/TinyGPSPlus.git#254a10041ac38d17d98dab24c0ae4d2a8d19a677
    jgromes/RadioLib@7.1.2
    earlephilhower/ESP8266Audio@1.9.7
    h2zero/NimBLE-Arduino@2.5.1
    ewpa/LibSSH-ESP32@3.1.0
    bblanchon/ArduinoJson@7.4.2
extra_scripts =
    pre:patch_wifi_lib.py

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_src_filter =
    +<eapol_parser.cpp>
    +<ota_version.cpp>
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror
